# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/boundaries", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Boundary. As you add validations to Boundary, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Boundary.create! valid_attributes
      get boundaries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      boundary = Boundary.create! valid_attributes
      get boundary_url(boundary)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_boundary_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      boundary = Boundary.create! valid_attributes
      get edit_boundary_url(boundary)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Boundary" do
        expect do
          post boundaries_url, params: {boundary: valid_attributes}
        end.to change(Boundary, :count).by(1)
      end

      it "redirects to the created boundary" do
        post boundaries_url, params: {boundary: valid_attributes}
        expect(response).to redirect_to(boundary_url(Boundary.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Boundary" do
        expect do
          post boundaries_url, params: {boundary: invalid_attributes}
        end.to change(Boundary, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post boundaries_url, params: {boundary: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested boundary" do
        boundary = Boundary.create! valid_attributes
        patch boundary_url(boundary), params: {boundary: new_attributes}
        boundary.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the boundary" do
        boundary = Boundary.create! valid_attributes
        patch boundary_url(boundary), params: {boundary: new_attributes}
        boundary.reload
        expect(response).to redirect_to(boundary_url(boundary))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        boundary = Boundary.create! valid_attributes
        patch boundary_url(boundary), params: {boundary: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested boundary" do
      boundary = Boundary.create! valid_attributes
      expect do
        delete boundary_url(boundary)
      end.to change(Boundary, :count).by(-1)
    end

    it "redirects to the boundaries list" do
      boundary = Boundary.create! valid_attributes
      delete boundary_url(boundary)
      expect(response).to redirect_to(boundaries_url)
    end
  end
end
