# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.18
        uses: actions/setup-node@v4
        with:
          node-version: 20.18
          cache: "npm"
      - run: npm ci
      - run: npx eslint .
      - run: npx prettier --check .
